default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    []

  javascripts:    [http://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js]

  has_layout:     true
  layout:         layout
