<?php


/**
 * This class adds structure of 'item2item' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Mon Feb 28 06:46:51 2011
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class Item2itemMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.Item2itemMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(Item2itemPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(Item2itemPeer::TABLE_NAME);
		$tMap->setPhpName('Item2item');
		$tMap->setClassname('Item2item');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addColumn('ITEM1_ID', 'Item1Id', 'INTEGER', true, null);

		$tMap->addForeignKey('ITEM1_TYPE', 'Item1Type', 'INTEGER', 'itemtypes', 'ID', true, null);

		$tMap->addColumn('ITEM2_ID', 'Item2Id', 'INTEGER', true, null);

		$tMap->addForeignKey('ITEM2_TYPE', 'Item2Type', 'INTEGER', 'itemtypes', 'ID', true, null);

	} // doBuild()

} // Item2itemMapBuilder
