<?php


/**
 * This class defines the structure of the 'photo' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Nov  2 11:42:27 2011
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class PhotoTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.PhotoTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('photo');
		$this->setPhpName('Photo');
		$this->setClassname('Photo');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addForeignKey('PHOTOALBUM_ID', 'PhotoalbumId', 'INTEGER', 'photoalbum', 'ID', false, null, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('SHOW', 'Show', 'BOOLEAN', false, null, true);
		$this->addColumn('ORDER', 'Order', 'INTEGER', true, null, null);
		$this->addColumn('IMG', 'Img', 'VARCHAR', false, 255, null);
		$this->addColumn('FULL_PATH', 'FullPath', 'VARCHAR', false, 255, null);
		$this->addColumn('PREVIEW_PATH', 'PreviewPath', 'VARCHAR', false, 255, null);
		$this->addColumn('THUMB_PATH', 'ThumbPath', 'VARCHAR', false, 255, null);
		$this->addColumn('LINK', 'Link', 'VARCHAR', false, 255, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Photoalbum', 'Photoalbum', RelationMap::MANY_TO_ONE, array('photoalbum_id' => 'id', ), null, null);
    $this->addRelation('PhotoI18n', 'PhotoI18n', RelationMap::ONE_TO_MANY, array('id' => 'id', ), 'CASCADE', null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
			'symfony_i18n' => array('i18n_table' => 'photo_i18n', ),
		);
	} // getBehaviors()

} // PhotoTableMap
