<?php


/**
 * This class defines the structure of the 'phpb7d3x_sessions' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Mar 14 05:57:47 2011
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class Phpb7d3xSessionsTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.Phpb7d3xSessionsTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('phpb7d3x_sessions');
		$this->setPhpName('Phpb7d3xSessions');
		$this->setClassname('Phpb7d3xSessions');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(false);
		// columns
		$this->addPrimaryKey('SESSION_ID', 'SessionId', 'VARCHAR', true, 32, null);
		$this->addColumn('SESSION_USER_ID', 'SessionUserId', 'INTEGER', false, null, 0);
		$this->addColumn('SESSION_FORUM_ID', 'SessionForumId', 'INTEGER', false, null, 0);
		$this->addColumn('SESSION_LAST_VISIT', 'SessionLastVisit', 'INTEGER', false, null, 0);
		$this->addColumn('SESSION_START', 'SessionStart', 'INTEGER', false, null, 0);
		$this->addColumn('SESSION_TIME', 'SessionTime', 'INTEGER', false, null, 0);
		$this->addColumn('SESSION_IP', 'SessionIp', 'VARCHAR', false, 40, '');
		$this->addColumn('SESSION_BROWSER', 'SessionBrowser', 'VARCHAR', false, 150, '');
		$this->addColumn('SESSION_FORWARDED_FOR', 'SessionForwardedFor', 'VARCHAR', false, 255, '');
		$this->addColumn('SESSION_PAGE', 'SessionPage', 'VARCHAR', false, 255, '');
		$this->addColumn('SESSION_VIEWONLINE', 'SessionViewonline', 'TINYINT', false, null, 1);
		$this->addColumn('SESSION_AUTOLOGIN', 'SessionAutologin', 'TINYINT', false, null, 0);
		$this->addColumn('SESSION_ADMIN', 'SessionAdmin', 'TINYINT', false, null, 0);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // Phpb7d3xSessionsTableMap
