<?php


/**
 * This class adds structure of 'phpb7d3x_users' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Mon Feb 28 06:46:52 2011
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class Phpb7d3xUsersMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.Phpb7d3xUsersMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(Phpb7d3xUsersPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(Phpb7d3xUsersPeer::TABLE_NAME);
		$tMap->setPhpName('Phpb7d3xUsers');
		$tMap->setClassname('Phpb7d3xUsers');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('USER_ID', 'UserId', 'INTEGER', true, null);

		$tMap->addColumn('USER_TYPE', 'UserType', 'TINYINT', false, null);

		$tMap->addColumn('GROUP_ID', 'GroupId', 'INTEGER', false, null);

		$tMap->addColumn('USER_PERMISSIONS', 'UserPermissions', 'LONGVARCHAR', false, null);

		$tMap->addColumn('USER_PERM_FROM', 'UserPermFrom', 'INTEGER', false, null);

		$tMap->addColumn('USER_IP', 'UserIp', 'VARCHAR', false, 40);

		$tMap->addColumn('USER_REGDATE', 'UserRegdate', 'INTEGER', false, null);

		$tMap->addColumn('USERNAME', 'Username', 'VARCHAR', false, 255);

		$tMap->addColumn('USERNAME_CLEAN', 'UsernameClean', 'VARCHAR', false, 255);

		$tMap->addColumn('USER_PASSWORD', 'UserPassword', 'VARCHAR', false, 40);

		$tMap->addColumn('USER_EMAIL', 'UserEmail', 'VARCHAR', false, 100);

		$tMap->addColumn('USER_EMAIL_HASH', 'UserEmailHash', 'BIGINT', false, null);

	} // doBuild()

} // Phpb7d3xUsersMapBuilder
