<?php


/**
 * This class adds structure of 'phpb7d3x_sessions' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Mon Feb 28 06:46:52 2011
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class Phpb7d3xSessionsMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.Phpb7d3xSessionsMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(Phpb7d3xSessionsPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(Phpb7d3xSessionsPeer::TABLE_NAME);
		$tMap->setPhpName('Phpb7d3xSessions');
		$tMap->setClassname('Phpb7d3xSessions');

		$tMap->setUseIdGenerator(false);

		$tMap->addPrimaryKey('SESSION_ID', 'SessionId', 'VARCHAR', true, 32);

		$tMap->addColumn('SESSION_USER_ID', 'SessionUserId', 'INTEGER', false, null);

		$tMap->addColumn('SESSION_FORUM_ID', 'SessionForumId', 'INTEGER', false, null);

		$tMap->addColumn('SESSION_LAST_VISIT', 'SessionLastVisit', 'INTEGER', false, null);

		$tMap->addColumn('SESSION_START', 'SessionStart', 'INTEGER', false, null);

		$tMap->addColumn('SESSION_TIME', 'SessionTime', 'INTEGER', false, null);

		$tMap->addColumn('SESSION_IP', 'SessionIp', 'VARCHAR', false, 40);

		$tMap->addColumn('SESSION_BROWSER', 'SessionBrowser', 'VARCHAR', false, 150);

		$tMap->addColumn('SESSION_FORWARDED_FOR', 'SessionForwardedFor', 'VARCHAR', false, 255);

		$tMap->addColumn('SESSION_PAGE', 'SessionPage', 'VARCHAR', false, 255);

		$tMap->addColumn('SESSION_VIEWONLINE', 'SessionViewonline', 'TINYINT', false, null);

		$tMap->addColumn('SESSION_AUTOLOGIN', 'SessionAutologin', 'TINYINT', false, null);

		$tMap->addColumn('SESSION_ADMIN', 'SessionAdmin', 'TINYINT', false, null);

	} // doBuild()

} // Phpb7d3xSessionsMapBuilder
