<?php

/**
 * Base class that represents a row from the 'user' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sun Apr  3 12:43:37 2011
 *
 * @package    lib.model.om
 */
abstract class BaseUser extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        UserPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the timezone_id field.
	 * @var        int
	 */
	protected $timezone_id;

	/**
	 * The value for the name field.
	 * @var        string
	 */
	protected $name;

	/**
	 * The value for the email field.
	 * @var        string
	 */
	protected $email;

	/**
	 * The value for the password field.
	 * @var        string
	 */
	protected $password;

	/**
	 * The value for the profile field.
	 * @var        string
	 */
	protected $profile;

	/**
	 * The value for the is_active field.
	 * Note: this column has a database default value of: true
	 * @var        boolean
	 */
	protected $is_active;

	/**
	 * The value for the remember_me_code field.
	 * @var        string
	 */
	protected $remember_me_code;

	/**
	 * The value for the ip field.
	 * @var        string
	 */
	protected $ip;

	/**
	 * The value for the last_login field.
	 * @var        string
	 */
	protected $last_login;

	/**
	 * The value for the lang field.
	 * @var        string
	 */
	protected $lang;

	/**
	 * The value for the phpbb_id field.
	 * @var        int
	 */
	protected $phpbb_id;

	/**
	 * The value for the remind_code field.
	 * @var        string
	 */
	protected $remind_code;

	/**
	 * The value for the subscribe_news field.
	 * Note: this column has a database default value of: true
	 * @var        boolean
	 */
	protected $subscribe_news;

	/**
	 * The value for the subscribe_photo field.
	 * Note: this column has a database default value of: true
	 * @var        boolean
	 */
	protected $subscribe_photo;

	/**
	 * The value for the subscribe_video field.
	 * Note: this column has a database default value of: true
	 * @var        boolean
	 */
	protected $subscribe_video;

	/**
	 * The value for the notes field.
	 * @var        string
	 */
	protected $notes;

	/**
	 * @var        Timezone
	 */
	protected $aTimezone;

	/**
	 * @var        array Comments[] Collection to store aggregation of Comments objects.
	 */
	protected $collCommentss;

	/**
	 * @var        Criteria The criteria used to select the current contents of collCommentss.
	 */
	private $lastCommentsCriteria = null;

	/**
	 * @var        array Alert[] Collection to store aggregation of Alert objects.
	 */
	protected $collAlertsRelatedByUserId;

	/**
	 * @var        Criteria The criteria used to select the current contents of collAlertsRelatedByUserId.
	 */
	private $lastAlertRelatedByUserIdCriteria = null;

	/**
	 * @var        array Alert[] Collection to store aggregation of Alert objects.
	 */
	protected $collAlertsRelatedByItemByUser;

	/**
	 * @var        Criteria The criteria used to select the current contents of collAlertsRelatedByItemByUser.
	 */
	private $lastAlertRelatedByItemByUserCriteria = null;

	/**
	 * @var        array Subscribe[] Collection to store aggregation of Subscribe objects.
	 */
	protected $collSubscribes;

	/**
	 * @var        Criteria The criteria used to select the current contents of collSubscribes.
	 */
	private $lastSubscribeCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'UserPeer';

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->is_active = true;
		$this->subscribe_news = true;
		$this->subscribe_photo = true;
		$this->subscribe_video = true;
	}

	/**
	 * Initializes internal state of BaseUser object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [timezone_id] column value.
	 * 
	 * @return     int
	 */
	public function getTimezoneId()
	{
		return $this->timezone_id;
	}

	/**
	 * Get the [name] column value.
	 * 
	 * @return     string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Get the [email] column value.
	 * 
	 * @return     string
	 */
	public function getEmail()
	{
		return $this->email;
	}

	/**
	 * Get the [password] column value.
	 * 
	 * @return     string
	 */
	public function getPassword()
	{
		return $this->password;
	}

	/**
	 * Get the [profile] column value.
	 * 
	 * @return     string
	 */
	public function getProfile()
	{
		return $this->profile;
	}

	/**
	 * Get the [is_active] column value.
	 * 
	 * @return     boolean
	 */
	public function getIsActive()
	{
		return $this->is_active;
	}

	/**
	 * Get the [remember_me_code] column value.
	 * 
	 * @return     string
	 */
	public function getRememberMeCode()
	{
		return $this->remember_me_code;
	}

	/**
	 * Get the [ip] column value.
	 * 
	 * @return     string
	 */
	public function getIp()
	{
		return $this->ip;
	}

	/**
	 * Get the [optionally formatted] temporal [last_login] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getLastLogin($format = 'Y-m-d H:i:s')
	{
		if ($this->last_login === null) {
			return null;
		}


		if ($this->last_login === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->last_login);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->last_login, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [lang] column value.
	 * 
	 * @return     string
	 */
	public function getLang()
	{
		return $this->lang;
	}

	/**
	 * Get the [phpbb_id] column value.
	 * 
	 * @return     int
	 */
	public function getPhpbbId()
	{
		return $this->phpbb_id;
	}

	/**
	 * Get the [remind_code] column value.
	 * 
	 * @return     string
	 */
	public function getRemindCode()
	{
		return $this->remind_code;
	}

	/**
	 * Get the [subscribe_news] column value.
	 * 
	 * @return     boolean
	 */
	public function getSubscribeNews()
	{
		return $this->subscribe_news;
	}

	/**
	 * Get the [subscribe_photo] column value.
	 * 
	 * @return     boolean
	 */
	public function getSubscribePhoto()
	{
		return $this->subscribe_photo;
	}

	/**
	 * Get the [subscribe_video] column value.
	 * 
	 * @return     boolean
	 */
	public function getSubscribeVideo()
	{
		return $this->subscribe_video;
	}

	/**
	 * Get the [notes] column value.
	 * 
	 * @return     string
	 */
	public function getNotes()
	{
		return $this->notes;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     User The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = UserPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     User The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = UserPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Set the value of [timezone_id] column.
	 * 
	 * @param      int $v new value
	 * @return     User The current object (for fluent API support)
	 */
	public function setTimezoneId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->timezone_id !== $v) {
			$this->timezone_id = $v;
			$this->modifiedColumns[] = UserPeer::TIMEZONE_ID;
		}

		if ($this->aTimezone !== null && $this->aTimezone->getId() !== $v) {
			$this->aTimezone = null;
		}

		return $this;
	} // setTimezoneId()

	/**
	 * Set the value of [name] column.
	 * 
	 * @param      string $v new value
	 * @return     User The current object (for fluent API support)
	 */
	public function setName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->name !== $v) {
			$this->name = $v;
			$this->modifiedColumns[] = UserPeer::NAME;
		}

		return $this;
	} // setName()

	/**
	 * Set the value of [email] column.
	 * 
	 * @param      string $v new value
	 * @return     User The current object (for fluent API support)
	 */
	public function setEmail($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->email !== $v) {
			$this->email = $v;
			$this->modifiedColumns[] = UserPeer::EMAIL;
		}

		return $this;
	} // setEmail()

	/**
	 * Set the value of [password] column.
	 * 
	 * @param      string $v new value
	 * @return     User The current object (for fluent API support)
	 */
	public function setPassword($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->password !== $v) {
			$this->password = $v;
			$this->modifiedColumns[] = UserPeer::PASSWORD;
		}

		return $this;
	} // setPassword()

	/**
	 * Set the value of [profile] column.
	 * 
	 * @param      string $v new value
	 * @return     User The current object (for fluent API support)
	 */
	public function setProfile($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->profile !== $v) {
			$this->profile = $v;
			$this->modifiedColumns[] = UserPeer::PROFILE;
		}

		return $this;
	} // setProfile()

	/**
	 * Set the value of [is_active] column.
	 * 
	 * @param      boolean $v new value
	 * @return     User The current object (for fluent API support)
	 */
	public function setIsActive($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->is_active !== $v || $this->isNew()) {
			$this->is_active = $v;
			$this->modifiedColumns[] = UserPeer::IS_ACTIVE;
		}

		return $this;
	} // setIsActive()

	/**
	 * Set the value of [remember_me_code] column.
	 * 
	 * @param      string $v new value
	 * @return     User The current object (for fluent API support)
	 */
	public function setRememberMeCode($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->remember_me_code !== $v) {
			$this->remember_me_code = $v;
			$this->modifiedColumns[] = UserPeer::REMEMBER_ME_CODE;
		}

		return $this;
	} // setRememberMeCode()

	/**
	 * Set the value of [ip] column.
	 * 
	 * @param      string $v new value
	 * @return     User The current object (for fluent API support)
	 */
	public function setIp($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->ip !== $v) {
			$this->ip = $v;
			$this->modifiedColumns[] = UserPeer::IP;
		}

		return $this;
	} // setIp()

	/**
	 * Sets the value of [last_login] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     User The current object (for fluent API support)
	 */
	public function setLastLogin($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->last_login !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->last_login !== null && $tmpDt = new DateTime($this->last_login)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->last_login = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = UserPeer::LAST_LOGIN;
			}
		} // if either are not null

		return $this;
	} // setLastLogin()

	/**
	 * Set the value of [lang] column.
	 * 
	 * @param      string $v new value
	 * @return     User The current object (for fluent API support)
	 */
	public function setLang($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->lang !== $v) {
			$this->lang = $v;
			$this->modifiedColumns[] = UserPeer::LANG;
		}

		return $this;
	} // setLang()

	/**
	 * Set the value of [phpbb_id] column.
	 * 
	 * @param      int $v new value
	 * @return     User The current object (for fluent API support)
	 */
	public function setPhpbbId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->phpbb_id !== $v) {
			$this->phpbb_id = $v;
			$this->modifiedColumns[] = UserPeer::PHPBB_ID;
		}

		return $this;
	} // setPhpbbId()

	/**
	 * Set the value of [remind_code] column.
	 * 
	 * @param      string $v new value
	 * @return     User The current object (for fluent API support)
	 */
	public function setRemindCode($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->remind_code !== $v) {
			$this->remind_code = $v;
			$this->modifiedColumns[] = UserPeer::REMIND_CODE;
		}

		return $this;
	} // setRemindCode()

	/**
	 * Set the value of [subscribe_news] column.
	 * 
	 * @param      boolean $v new value
	 * @return     User The current object (for fluent API support)
	 */
	public function setSubscribeNews($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->subscribe_news !== $v || $this->isNew()) {
			$this->subscribe_news = $v;
			$this->modifiedColumns[] = UserPeer::SUBSCRIBE_NEWS;
		}

		return $this;
	} // setSubscribeNews()

	/**
	 * Set the value of [subscribe_photo] column.
	 * 
	 * @param      boolean $v new value
	 * @return     User The current object (for fluent API support)
	 */
	public function setSubscribePhoto($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->subscribe_photo !== $v || $this->isNew()) {
			$this->subscribe_photo = $v;
			$this->modifiedColumns[] = UserPeer::SUBSCRIBE_PHOTO;
		}

		return $this;
	} // setSubscribePhoto()

	/**
	 * Set the value of [subscribe_video] column.
	 * 
	 * @param      boolean $v new value
	 * @return     User The current object (for fluent API support)
	 */
	public function setSubscribeVideo($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->subscribe_video !== $v || $this->isNew()) {
			$this->subscribe_video = $v;
			$this->modifiedColumns[] = UserPeer::SUBSCRIBE_VIDEO;
		}

		return $this;
	} // setSubscribeVideo()

	/**
	 * Set the value of [notes] column.
	 * 
	 * @param      string $v new value
	 * @return     User The current object (for fluent API support)
	 */
	public function setNotes($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->notes !== $v) {
			$this->notes = $v;
			$this->modifiedColumns[] = UserPeer::NOTES;
		}

		return $this;
	} // setNotes()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			if ($this->is_active !== true) {
				return false;
			}

			if ($this->subscribe_news !== true) {
				return false;
			}

			if ($this->subscribe_photo !== true) {
				return false;
			}

			if ($this->subscribe_video !== true) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->created_at = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->timezone_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->name = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->email = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->password = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->profile = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->is_active = ($row[$startcol + 7] !== null) ? (boolean) $row[$startcol + 7] : null;
			$this->remember_me_code = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->ip = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->last_login = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->lang = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->phpbb_id = ($row[$startcol + 12] !== null) ? (int) $row[$startcol + 12] : null;
			$this->remind_code = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->subscribe_news = ($row[$startcol + 14] !== null) ? (boolean) $row[$startcol + 14] : null;
			$this->subscribe_photo = ($row[$startcol + 15] !== null) ? (boolean) $row[$startcol + 15] : null;
			$this->subscribe_video = ($row[$startcol + 16] !== null) ? (boolean) $row[$startcol + 16] : null;
			$this->notes = ($row[$startcol + 17] !== null) ? (string) $row[$startcol + 17] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 18; // 18 = UserPeer::NUM_COLUMNS - UserPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating User object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aTimezone !== null && $this->timezone_id !== $this->aTimezone->getId()) {
			$this->aTimezone = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UserPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = UserPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aTimezone = null;
			$this->collCommentss = null;
			$this->lastCommentsCriteria = null;

			$this->collAlertsRelatedByUserId = null;
			$this->lastAlertRelatedByUserIdCriteria = null;

			$this->collAlertsRelatedByItemByUser = null;
			$this->lastAlertRelatedByItemByUserCriteria = null;

			$this->collSubscribes = null;
			$this->lastSubscribeCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UserPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseUser:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				UserPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseUser:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UserPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseUser:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			// symfony_timestampable behavior
			
			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// symfony_timestampable behavior
				if (!$this->isColumnModified(UserPeer::CREATED_AT))
				{
				  $this->setCreatedAt(time());
				}

			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseUser:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				UserPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aTimezone !== null) {
				if ($this->aTimezone->isModified() || $this->aTimezone->isNew()) {
					$affectedRows += $this->aTimezone->save($con);
				}
				$this->setTimezone($this->aTimezone);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = UserPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = UserPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += UserPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collCommentss !== null) {
				foreach ($this->collCommentss as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collAlertsRelatedByUserId !== null) {
				foreach ($this->collAlertsRelatedByUserId as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collAlertsRelatedByItemByUser !== null) {
				foreach ($this->collAlertsRelatedByItemByUser as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collSubscribes !== null) {
				foreach ($this->collSubscribes as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aTimezone !== null) {
				if (!$this->aTimezone->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aTimezone->getValidationFailures());
				}
			}


			if (($retval = UserPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collCommentss !== null) {
					foreach ($this->collCommentss as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collAlertsRelatedByUserId !== null) {
					foreach ($this->collAlertsRelatedByUserId as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collAlertsRelatedByItemByUser !== null) {
					foreach ($this->collAlertsRelatedByItemByUser as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collSubscribes !== null) {
					foreach ($this->collSubscribes as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = UserPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getCreatedAt();
				break;
			case 2:
				return $this->getTimezoneId();
				break;
			case 3:
				return $this->getName();
				break;
			case 4:
				return $this->getEmail();
				break;
			case 5:
				return $this->getPassword();
				break;
			case 6:
				return $this->getProfile();
				break;
			case 7:
				return $this->getIsActive();
				break;
			case 8:
				return $this->getRememberMeCode();
				break;
			case 9:
				return $this->getIp();
				break;
			case 10:
				return $this->getLastLogin();
				break;
			case 11:
				return $this->getLang();
				break;
			case 12:
				return $this->getPhpbbId();
				break;
			case 13:
				return $this->getRemindCode();
				break;
			case 14:
				return $this->getSubscribeNews();
				break;
			case 15:
				return $this->getSubscribePhoto();
				break;
			case 16:
				return $this->getSubscribeVideo();
				break;
			case 17:
				return $this->getNotes();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = UserPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getCreatedAt(),
			$keys[2] => $this->getTimezoneId(),
			$keys[3] => $this->getName(),
			$keys[4] => $this->getEmail(),
			$keys[5] => $this->getPassword(),
			$keys[6] => $this->getProfile(),
			$keys[7] => $this->getIsActive(),
			$keys[8] => $this->getRememberMeCode(),
			$keys[9] => $this->getIp(),
			$keys[10] => $this->getLastLogin(),
			$keys[11] => $this->getLang(),
			$keys[12] => $this->getPhpbbId(),
			$keys[13] => $this->getRemindCode(),
			$keys[14] => $this->getSubscribeNews(),
			$keys[15] => $this->getSubscribePhoto(),
			$keys[16] => $this->getSubscribeVideo(),
			$keys[17] => $this->getNotes(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = UserPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setCreatedAt($value);
				break;
			case 2:
				$this->setTimezoneId($value);
				break;
			case 3:
				$this->setName($value);
				break;
			case 4:
				$this->setEmail($value);
				break;
			case 5:
				$this->setPassword($value);
				break;
			case 6:
				$this->setProfile($value);
				break;
			case 7:
				$this->setIsActive($value);
				break;
			case 8:
				$this->setRememberMeCode($value);
				break;
			case 9:
				$this->setIp($value);
				break;
			case 10:
				$this->setLastLogin($value);
				break;
			case 11:
				$this->setLang($value);
				break;
			case 12:
				$this->setPhpbbId($value);
				break;
			case 13:
				$this->setRemindCode($value);
				break;
			case 14:
				$this->setSubscribeNews($value);
				break;
			case 15:
				$this->setSubscribePhoto($value);
				break;
			case 16:
				$this->setSubscribeVideo($value);
				break;
			case 17:
				$this->setNotes($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = UserPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setCreatedAt($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setTimezoneId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setName($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setEmail($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setPassword($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setProfile($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setIsActive($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setRememberMeCode($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setIp($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setLastLogin($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setLang($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setPhpbbId($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setRemindCode($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setSubscribeNews($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setSubscribePhoto($arr[$keys[15]]);
		if (array_key_exists($keys[16], $arr)) $this->setSubscribeVideo($arr[$keys[16]]);
		if (array_key_exists($keys[17], $arr)) $this->setNotes($arr[$keys[17]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(UserPeer::DATABASE_NAME);

		if ($this->isColumnModified(UserPeer::ID)) $criteria->add(UserPeer::ID, $this->id);
		if ($this->isColumnModified(UserPeer::CREATED_AT)) $criteria->add(UserPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(UserPeer::TIMEZONE_ID)) $criteria->add(UserPeer::TIMEZONE_ID, $this->timezone_id);
		if ($this->isColumnModified(UserPeer::NAME)) $criteria->add(UserPeer::NAME, $this->name);
		if ($this->isColumnModified(UserPeer::EMAIL)) $criteria->add(UserPeer::EMAIL, $this->email);
		if ($this->isColumnModified(UserPeer::PASSWORD)) $criteria->add(UserPeer::PASSWORD, $this->password);
		if ($this->isColumnModified(UserPeer::PROFILE)) $criteria->add(UserPeer::PROFILE, $this->profile);
		if ($this->isColumnModified(UserPeer::IS_ACTIVE)) $criteria->add(UserPeer::IS_ACTIVE, $this->is_active);
		if ($this->isColumnModified(UserPeer::REMEMBER_ME_CODE)) $criteria->add(UserPeer::REMEMBER_ME_CODE, $this->remember_me_code);
		if ($this->isColumnModified(UserPeer::IP)) $criteria->add(UserPeer::IP, $this->ip);
		if ($this->isColumnModified(UserPeer::LAST_LOGIN)) $criteria->add(UserPeer::LAST_LOGIN, $this->last_login);
		if ($this->isColumnModified(UserPeer::LANG)) $criteria->add(UserPeer::LANG, $this->lang);
		if ($this->isColumnModified(UserPeer::PHPBB_ID)) $criteria->add(UserPeer::PHPBB_ID, $this->phpbb_id);
		if ($this->isColumnModified(UserPeer::REMIND_CODE)) $criteria->add(UserPeer::REMIND_CODE, $this->remind_code);
		if ($this->isColumnModified(UserPeer::SUBSCRIBE_NEWS)) $criteria->add(UserPeer::SUBSCRIBE_NEWS, $this->subscribe_news);
		if ($this->isColumnModified(UserPeer::SUBSCRIBE_PHOTO)) $criteria->add(UserPeer::SUBSCRIBE_PHOTO, $this->subscribe_photo);
		if ($this->isColumnModified(UserPeer::SUBSCRIBE_VIDEO)) $criteria->add(UserPeer::SUBSCRIBE_VIDEO, $this->subscribe_video);
		if ($this->isColumnModified(UserPeer::NOTES)) $criteria->add(UserPeer::NOTES, $this->notes);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(UserPeer::DATABASE_NAME);

		$criteria->add(UserPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of User (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setTimezoneId($this->timezone_id);

		$copyObj->setName($this->name);

		$copyObj->setEmail($this->email);

		$copyObj->setPassword($this->password);

		$copyObj->setProfile($this->profile);

		$copyObj->setIsActive($this->is_active);

		$copyObj->setRememberMeCode($this->remember_me_code);

		$copyObj->setIp($this->ip);

		$copyObj->setLastLogin($this->last_login);

		$copyObj->setLang($this->lang);

		$copyObj->setPhpbbId($this->phpbb_id);

		$copyObj->setRemindCode($this->remind_code);

		$copyObj->setSubscribeNews($this->subscribe_news);

		$copyObj->setSubscribePhoto($this->subscribe_photo);

		$copyObj->setSubscribeVideo($this->subscribe_video);

		$copyObj->setNotes($this->notes);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getCommentss() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addComments($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getAlertsRelatedByUserId() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addAlertRelatedByUserId($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getAlertsRelatedByItemByUser() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addAlertRelatedByItemByUser($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getSubscribes() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addSubscribe($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     User Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     UserPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new UserPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Timezone object.
	 *
	 * @param      Timezone $v
	 * @return     User The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setTimezone(Timezone $v = null)
	{
		if ($v === null) {
			$this->setTimezoneId(NULL);
		} else {
			$this->setTimezoneId($v->getId());
		}

		$this->aTimezone = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Timezone object, it will not be re-added.
		if ($v !== null) {
			$v->addUser($this);
		}

		return $this;
	}


	/**
	 * Get the associated Timezone object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Timezone The associated Timezone object.
	 * @throws     PropelException
	 */
	public function getTimezone(PropelPDO $con = null)
	{
		if ($this->aTimezone === null && ($this->timezone_id !== null)) {
			$this->aTimezone = TimezonePeer::retrieveByPk($this->timezone_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aTimezone->addUsers($this);
			 */
		}
		return $this->aTimezone;
	}

	/**
	 * Clears out the collCommentss collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addCommentss()
	 */
	public function clearCommentss()
	{
		$this->collCommentss = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collCommentss collection (array).
	 *
	 * By default this just sets the collCommentss collection to an empty array (like clearcollCommentss());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initCommentss()
	{
		$this->collCommentss = array();
	}

	/**
	 * Gets an array of Comments objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this User has previously been saved, it will retrieve
	 * related Commentss from storage. If this User is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Comments[]
	 * @throws     PropelException
	 */
	public function getCommentss($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCommentss === null) {
			if ($this->isNew()) {
			   $this->collCommentss = array();
			} else {

				$criteria->add(CommentsPeer::USER_ID, $this->id);

				CommentsPeer::addSelectColumns($criteria);
				$this->collCommentss = CommentsPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(CommentsPeer::USER_ID, $this->id);

				CommentsPeer::addSelectColumns($criteria);
				if (!isset($this->lastCommentsCriteria) || !$this->lastCommentsCriteria->equals($criteria)) {
					$this->collCommentss = CommentsPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastCommentsCriteria = $criteria;
		return $this->collCommentss;
	}

	/**
	 * Returns the number of related Comments objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Comments objects.
	 * @throws     PropelException
	 */
	public function countCommentss(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collCommentss === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(CommentsPeer::USER_ID, $this->id);

				$count = CommentsPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(CommentsPeer::USER_ID, $this->id);

				if (!isset($this->lastCommentsCriteria) || !$this->lastCommentsCriteria->equals($criteria)) {
					$count = CommentsPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collCommentss);
				}
			} else {
				$count = count($this->collCommentss);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Comments object to this object
	 * through the Comments foreign key attribute.
	 *
	 * @param      Comments $l Comments
	 * @return     void
	 * @throws     PropelException
	 */
	public function addComments(Comments $l)
	{
		if ($this->collCommentss === null) {
			$this->initCommentss();
		}
		if (!in_array($l, $this->collCommentss, true)) { // only add it if the **same** object is not already associated
			array_push($this->collCommentss, $l);
			$l->setUser($this);
		}
	}

	/**
	 * Clears out the collAlertsRelatedByUserId collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addAlertsRelatedByUserId()
	 */
	public function clearAlertsRelatedByUserId()
	{
		$this->collAlertsRelatedByUserId = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collAlertsRelatedByUserId collection (array).
	 *
	 * By default this just sets the collAlertsRelatedByUserId collection to an empty array (like clearcollAlertsRelatedByUserId());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initAlertsRelatedByUserId()
	{
		$this->collAlertsRelatedByUserId = array();
	}

	/**
	 * Gets an array of Alert objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this User has previously been saved, it will retrieve
	 * related AlertsRelatedByUserId from storage. If this User is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Alert[]
	 * @throws     PropelException
	 */
	public function getAlertsRelatedByUserId($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAlertsRelatedByUserId === null) {
			if ($this->isNew()) {
			   $this->collAlertsRelatedByUserId = array();
			} else {

				$criteria->add(AlertPeer::USER_ID, $this->id);

				AlertPeer::addSelectColumns($criteria);
				$this->collAlertsRelatedByUserId = AlertPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(AlertPeer::USER_ID, $this->id);

				AlertPeer::addSelectColumns($criteria);
				if (!isset($this->lastAlertRelatedByUserIdCriteria) || !$this->lastAlertRelatedByUserIdCriteria->equals($criteria)) {
					$this->collAlertsRelatedByUserId = AlertPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastAlertRelatedByUserIdCriteria = $criteria;
		return $this->collAlertsRelatedByUserId;
	}

	/**
	 * Returns the number of related Alert objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Alert objects.
	 * @throws     PropelException
	 */
	public function countAlertsRelatedByUserId(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collAlertsRelatedByUserId === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(AlertPeer::USER_ID, $this->id);

				$count = AlertPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(AlertPeer::USER_ID, $this->id);

				if (!isset($this->lastAlertRelatedByUserIdCriteria) || !$this->lastAlertRelatedByUserIdCriteria->equals($criteria)) {
					$count = AlertPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collAlertsRelatedByUserId);
				}
			} else {
				$count = count($this->collAlertsRelatedByUserId);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Alert object to this object
	 * through the Alert foreign key attribute.
	 *
	 * @param      Alert $l Alert
	 * @return     void
	 * @throws     PropelException
	 */
	public function addAlertRelatedByUserId(Alert $l)
	{
		if ($this->collAlertsRelatedByUserId === null) {
			$this->initAlertsRelatedByUserId();
		}
		if (!in_array($l, $this->collAlertsRelatedByUserId, true)) { // only add it if the **same** object is not already associated
			array_push($this->collAlertsRelatedByUserId, $l);
			$l->setUserRelatedByUserId($this);
		}
	}

	/**
	 * Clears out the collAlertsRelatedByItemByUser collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addAlertsRelatedByItemByUser()
	 */
	public function clearAlertsRelatedByItemByUser()
	{
		$this->collAlertsRelatedByItemByUser = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collAlertsRelatedByItemByUser collection (array).
	 *
	 * By default this just sets the collAlertsRelatedByItemByUser collection to an empty array (like clearcollAlertsRelatedByItemByUser());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initAlertsRelatedByItemByUser()
	{
		$this->collAlertsRelatedByItemByUser = array();
	}

	/**
	 * Gets an array of Alert objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this User has previously been saved, it will retrieve
	 * related AlertsRelatedByItemByUser from storage. If this User is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Alert[]
	 * @throws     PropelException
	 */
	public function getAlertsRelatedByItemByUser($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAlertsRelatedByItemByUser === null) {
			if ($this->isNew()) {
			   $this->collAlertsRelatedByItemByUser = array();
			} else {

				$criteria->add(AlertPeer::ITEM_BY_USER, $this->id);

				AlertPeer::addSelectColumns($criteria);
				$this->collAlertsRelatedByItemByUser = AlertPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(AlertPeer::ITEM_BY_USER, $this->id);

				AlertPeer::addSelectColumns($criteria);
				if (!isset($this->lastAlertRelatedByItemByUserCriteria) || !$this->lastAlertRelatedByItemByUserCriteria->equals($criteria)) {
					$this->collAlertsRelatedByItemByUser = AlertPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastAlertRelatedByItemByUserCriteria = $criteria;
		return $this->collAlertsRelatedByItemByUser;
	}

	/**
	 * Returns the number of related Alert objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Alert objects.
	 * @throws     PropelException
	 */
	public function countAlertsRelatedByItemByUser(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collAlertsRelatedByItemByUser === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(AlertPeer::ITEM_BY_USER, $this->id);

				$count = AlertPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(AlertPeer::ITEM_BY_USER, $this->id);

				if (!isset($this->lastAlertRelatedByItemByUserCriteria) || !$this->lastAlertRelatedByItemByUserCriteria->equals($criteria)) {
					$count = AlertPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collAlertsRelatedByItemByUser);
				}
			} else {
				$count = count($this->collAlertsRelatedByItemByUser);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Alert object to this object
	 * through the Alert foreign key attribute.
	 *
	 * @param      Alert $l Alert
	 * @return     void
	 * @throws     PropelException
	 */
	public function addAlertRelatedByItemByUser(Alert $l)
	{
		if ($this->collAlertsRelatedByItemByUser === null) {
			$this->initAlertsRelatedByItemByUser();
		}
		if (!in_array($l, $this->collAlertsRelatedByItemByUser, true)) { // only add it if the **same** object is not already associated
			array_push($this->collAlertsRelatedByItemByUser, $l);
			$l->setUserRelatedByItemByUser($this);
		}
	}

	/**
	 * Clears out the collSubscribes collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addSubscribes()
	 */
	public function clearSubscribes()
	{
		$this->collSubscribes = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collSubscribes collection (array).
	 *
	 * By default this just sets the collSubscribes collection to an empty array (like clearcollSubscribes());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initSubscribes()
	{
		$this->collSubscribes = array();
	}

	/**
	 * Gets an array of Subscribe objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this User has previously been saved, it will retrieve
	 * related Subscribes from storage. If this User is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Subscribe[]
	 * @throws     PropelException
	 */
	public function getSubscribes($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSubscribes === null) {
			if ($this->isNew()) {
			   $this->collSubscribes = array();
			} else {

				$criteria->add(SubscribePeer::USER_ID, $this->id);

				SubscribePeer::addSelectColumns($criteria);
				$this->collSubscribes = SubscribePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(SubscribePeer::USER_ID, $this->id);

				SubscribePeer::addSelectColumns($criteria);
				if (!isset($this->lastSubscribeCriteria) || !$this->lastSubscribeCriteria->equals($criteria)) {
					$this->collSubscribes = SubscribePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastSubscribeCriteria = $criteria;
		return $this->collSubscribes;
	}

	/**
	 * Returns the number of related Subscribe objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Subscribe objects.
	 * @throws     PropelException
	 */
	public function countSubscribes(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collSubscribes === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(SubscribePeer::USER_ID, $this->id);

				$count = SubscribePeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(SubscribePeer::USER_ID, $this->id);

				if (!isset($this->lastSubscribeCriteria) || !$this->lastSubscribeCriteria->equals($criteria)) {
					$count = SubscribePeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collSubscribes);
				}
			} else {
				$count = count($this->collSubscribes);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Subscribe object to this object
	 * through the Subscribe foreign key attribute.
	 *
	 * @param      Subscribe $l Subscribe
	 * @return     void
	 * @throws     PropelException
	 */
	public function addSubscribe(Subscribe $l)
	{
		if ($this->collSubscribes === null) {
			$this->initSubscribes();
		}
		if (!in_array($l, $this->collSubscribes, true)) { // only add it if the **same** object is not already associated
			array_push($this->collSubscribes, $l);
			$l->setUser($this);
		}
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collCommentss) {
				foreach ((array) $this->collCommentss as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collAlertsRelatedByUserId) {
				foreach ((array) $this->collAlertsRelatedByUserId as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collAlertsRelatedByItemByUser) {
				foreach ((array) $this->collAlertsRelatedByItemByUser as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collSubscribes) {
				foreach ((array) $this->collSubscribes as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collCommentss = null;
		$this->collAlertsRelatedByUserId = null;
		$this->collAlertsRelatedByItemByUser = null;
		$this->collSubscribes = null;
			$this->aTimezone = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseUser:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseUser::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseUser
