<?php

/**
 * Base class that represents a row from the 'phpb7d3x_users' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Mar 14 05:57:47 2011
 *
 * @package    lib.model.om
 */
abstract class BasePhpb7d3xUsers extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        Phpb7d3xUsersPeer
	 */
	protected static $peer;

	/**
	 * The value for the user_id field.
	 * @var        int
	 */
	protected $user_id;

	/**
	 * The value for the user_type field.
	 * @var        int
	 */
	protected $user_type;

	/**
	 * The value for the group_id field.
	 * @var        int
	 */
	protected $group_id;

	/**
	 * The value for the user_permissions field.
	 * @var        string
	 */
	protected $user_permissions;

	/**
	 * The value for the user_perm_from field.
	 * @var        int
	 */
	protected $user_perm_from;

	/**
	 * The value for the user_ip field.
	 * @var        string
	 */
	protected $user_ip;

	/**
	 * The value for the user_regdate field.
	 * @var        int
	 */
	protected $user_regdate;

	/**
	 * The value for the username field.
	 * @var        string
	 */
	protected $username;

	/**
	 * The value for the username_clean field.
	 * @var        string
	 */
	protected $username_clean;

	/**
	 * The value for the user_password field.
	 * @var        string
	 */
	protected $user_password;

	/**
	 * The value for the user_email field.
	 * @var        string
	 */
	protected $user_email;

	/**
	 * The value for the user_email_hash field.
	 * @var        string
	 */
	protected $user_email_hash;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'Phpb7d3xUsersPeer';

	/**
	 * Get the [user_id] column value.
	 * 
	 * @return     int
	 */
	public function getUserId()
	{
		return $this->user_id;
	}

	/**
	 * Get the [user_type] column value.
	 * 
	 * @return     int
	 */
	public function getUserType()
	{
		return $this->user_type;
	}

	/**
	 * Get the [group_id] column value.
	 * 
	 * @return     int
	 */
	public function getGroupId()
	{
		return $this->group_id;
	}

	/**
	 * Get the [user_permissions] column value.
	 * 
	 * @return     string
	 */
	public function getUserPermissions()
	{
		return $this->user_permissions;
	}

	/**
	 * Get the [user_perm_from] column value.
	 * 
	 * @return     int
	 */
	public function getUserPermFrom()
	{
		return $this->user_perm_from;
	}

	/**
	 * Get the [user_ip] column value.
	 * 
	 * @return     string
	 */
	public function getUserIp()
	{
		return $this->user_ip;
	}

	/**
	 * Get the [user_regdate] column value.
	 * 
	 * @return     int
	 */
	public function getUserRegdate()
	{
		return $this->user_regdate;
	}

	/**
	 * Get the [username] column value.
	 * 
	 * @return     string
	 */
	public function getUsername()
	{
		return $this->username;
	}

	/**
	 * Get the [username_clean] column value.
	 * 
	 * @return     string
	 */
	public function getUsernameClean()
	{
		return $this->username_clean;
	}

	/**
	 * Get the [user_password] column value.
	 * 
	 * @return     string
	 */
	public function getUserPassword()
	{
		return $this->user_password;
	}

	/**
	 * Get the [user_email] column value.
	 * 
	 * @return     string
	 */
	public function getUserEmail()
	{
		return $this->user_email;
	}

	/**
	 * Get the [user_email_hash] column value.
	 * 
	 * @return     string
	 */
	public function getUserEmailHash()
	{
		return $this->user_email_hash;
	}

	/**
	 * Set the value of [user_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Phpb7d3xUsers The current object (for fluent API support)
	 */
	public function setUserId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->user_id !== $v) {
			$this->user_id = $v;
			$this->modifiedColumns[] = Phpb7d3xUsersPeer::USER_ID;
		}

		return $this;
	} // setUserId()

	/**
	 * Set the value of [user_type] column.
	 * 
	 * @param      int $v new value
	 * @return     Phpb7d3xUsers The current object (for fluent API support)
	 */
	public function setUserType($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->user_type !== $v) {
			$this->user_type = $v;
			$this->modifiedColumns[] = Phpb7d3xUsersPeer::USER_TYPE;
		}

		return $this;
	} // setUserType()

	/**
	 * Set the value of [group_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Phpb7d3xUsers The current object (for fluent API support)
	 */
	public function setGroupId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->group_id !== $v) {
			$this->group_id = $v;
			$this->modifiedColumns[] = Phpb7d3xUsersPeer::GROUP_ID;
		}

		return $this;
	} // setGroupId()

	/**
	 * Set the value of [user_permissions] column.
	 * 
	 * @param      string $v new value
	 * @return     Phpb7d3xUsers The current object (for fluent API support)
	 */
	public function setUserPermissions($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->user_permissions !== $v) {
			$this->user_permissions = $v;
			$this->modifiedColumns[] = Phpb7d3xUsersPeer::USER_PERMISSIONS;
		}

		return $this;
	} // setUserPermissions()

	/**
	 * Set the value of [user_perm_from] column.
	 * 
	 * @param      int $v new value
	 * @return     Phpb7d3xUsers The current object (for fluent API support)
	 */
	public function setUserPermFrom($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->user_perm_from !== $v) {
			$this->user_perm_from = $v;
			$this->modifiedColumns[] = Phpb7d3xUsersPeer::USER_PERM_FROM;
		}

		return $this;
	} // setUserPermFrom()

	/**
	 * Set the value of [user_ip] column.
	 * 
	 * @param      string $v new value
	 * @return     Phpb7d3xUsers The current object (for fluent API support)
	 */
	public function setUserIp($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->user_ip !== $v) {
			$this->user_ip = $v;
			$this->modifiedColumns[] = Phpb7d3xUsersPeer::USER_IP;
		}

		return $this;
	} // setUserIp()

	/**
	 * Set the value of [user_regdate] column.
	 * 
	 * @param      int $v new value
	 * @return     Phpb7d3xUsers The current object (for fluent API support)
	 */
	public function setUserRegdate($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->user_regdate !== $v) {
			$this->user_regdate = $v;
			$this->modifiedColumns[] = Phpb7d3xUsersPeer::USER_REGDATE;
		}

		return $this;
	} // setUserRegdate()

	/**
	 * Set the value of [username] column.
	 * 
	 * @param      string $v new value
	 * @return     Phpb7d3xUsers The current object (for fluent API support)
	 */
	public function setUsername($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->username !== $v) {
			$this->username = $v;
			$this->modifiedColumns[] = Phpb7d3xUsersPeer::USERNAME;
		}

		return $this;
	} // setUsername()

	/**
	 * Set the value of [username_clean] column.
	 * 
	 * @param      string $v new value
	 * @return     Phpb7d3xUsers The current object (for fluent API support)
	 */
	public function setUsernameClean($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->username_clean !== $v) {
			$this->username_clean = $v;
			$this->modifiedColumns[] = Phpb7d3xUsersPeer::USERNAME_CLEAN;
		}

		return $this;
	} // setUsernameClean()

	/**
	 * Set the value of [user_password] column.
	 * 
	 * @param      string $v new value
	 * @return     Phpb7d3xUsers The current object (for fluent API support)
	 */
	public function setUserPassword($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->user_password !== $v) {
			$this->user_password = $v;
			$this->modifiedColumns[] = Phpb7d3xUsersPeer::USER_PASSWORD;
		}

		return $this;
	} // setUserPassword()

	/**
	 * Set the value of [user_email] column.
	 * 
	 * @param      string $v new value
	 * @return     Phpb7d3xUsers The current object (for fluent API support)
	 */
	public function setUserEmail($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->user_email !== $v) {
			$this->user_email = $v;
			$this->modifiedColumns[] = Phpb7d3xUsersPeer::USER_EMAIL;
		}

		return $this;
	} // setUserEmail()

	/**
	 * Set the value of [user_email_hash] column.
	 * 
	 * @param      string $v new value
	 * @return     Phpb7d3xUsers The current object (for fluent API support)
	 */
	public function setUserEmailHash($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->user_email_hash !== $v) {
			$this->user_email_hash = $v;
			$this->modifiedColumns[] = Phpb7d3xUsersPeer::USER_EMAIL_HASH;
		}

		return $this;
	} // setUserEmailHash()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->user_id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->user_type = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->group_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->user_permissions = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->user_perm_from = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->user_ip = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->user_regdate = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->username = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->username_clean = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->user_password = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->user_email = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->user_email_hash = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 12; // 12 = Phpb7d3xUsersPeer::NUM_COLUMNS - Phpb7d3xUsersPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Phpb7d3xUsers object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(Phpb7d3xUsersPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = Phpb7d3xUsersPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(Phpb7d3xUsersPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BasePhpb7d3xUsers:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				Phpb7d3xUsersPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BasePhpb7d3xUsers:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(Phpb7d3xUsersPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BasePhpb7d3xUsers:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BasePhpb7d3xUsers:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				Phpb7d3xUsersPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = Phpb7d3xUsersPeer::USER_ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = Phpb7d3xUsersPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setUserId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += Phpb7d3xUsersPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = Phpb7d3xUsersPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = Phpb7d3xUsersPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getUserId();
				break;
			case 1:
				return $this->getUserType();
				break;
			case 2:
				return $this->getGroupId();
				break;
			case 3:
				return $this->getUserPermissions();
				break;
			case 4:
				return $this->getUserPermFrom();
				break;
			case 5:
				return $this->getUserIp();
				break;
			case 6:
				return $this->getUserRegdate();
				break;
			case 7:
				return $this->getUsername();
				break;
			case 8:
				return $this->getUsernameClean();
				break;
			case 9:
				return $this->getUserPassword();
				break;
			case 10:
				return $this->getUserEmail();
				break;
			case 11:
				return $this->getUserEmailHash();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = Phpb7d3xUsersPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getUserId(),
			$keys[1] => $this->getUserType(),
			$keys[2] => $this->getGroupId(),
			$keys[3] => $this->getUserPermissions(),
			$keys[4] => $this->getUserPermFrom(),
			$keys[5] => $this->getUserIp(),
			$keys[6] => $this->getUserRegdate(),
			$keys[7] => $this->getUsername(),
			$keys[8] => $this->getUsernameClean(),
			$keys[9] => $this->getUserPassword(),
			$keys[10] => $this->getUserEmail(),
			$keys[11] => $this->getUserEmailHash(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = Phpb7d3xUsersPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setUserId($value);
				break;
			case 1:
				$this->setUserType($value);
				break;
			case 2:
				$this->setGroupId($value);
				break;
			case 3:
				$this->setUserPermissions($value);
				break;
			case 4:
				$this->setUserPermFrom($value);
				break;
			case 5:
				$this->setUserIp($value);
				break;
			case 6:
				$this->setUserRegdate($value);
				break;
			case 7:
				$this->setUsername($value);
				break;
			case 8:
				$this->setUsernameClean($value);
				break;
			case 9:
				$this->setUserPassword($value);
				break;
			case 10:
				$this->setUserEmail($value);
				break;
			case 11:
				$this->setUserEmailHash($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = Phpb7d3xUsersPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setUserId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setUserType($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setGroupId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setUserPermissions($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setUserPermFrom($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setUserIp($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setUserRegdate($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setUsername($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setUsernameClean($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setUserPassword($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setUserEmail($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setUserEmailHash($arr[$keys[11]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(Phpb7d3xUsersPeer::DATABASE_NAME);

		if ($this->isColumnModified(Phpb7d3xUsersPeer::USER_ID)) $criteria->add(Phpb7d3xUsersPeer::USER_ID, $this->user_id);
		if ($this->isColumnModified(Phpb7d3xUsersPeer::USER_TYPE)) $criteria->add(Phpb7d3xUsersPeer::USER_TYPE, $this->user_type);
		if ($this->isColumnModified(Phpb7d3xUsersPeer::GROUP_ID)) $criteria->add(Phpb7d3xUsersPeer::GROUP_ID, $this->group_id);
		if ($this->isColumnModified(Phpb7d3xUsersPeer::USER_PERMISSIONS)) $criteria->add(Phpb7d3xUsersPeer::USER_PERMISSIONS, $this->user_permissions);
		if ($this->isColumnModified(Phpb7d3xUsersPeer::USER_PERM_FROM)) $criteria->add(Phpb7d3xUsersPeer::USER_PERM_FROM, $this->user_perm_from);
		if ($this->isColumnModified(Phpb7d3xUsersPeer::USER_IP)) $criteria->add(Phpb7d3xUsersPeer::USER_IP, $this->user_ip);
		if ($this->isColumnModified(Phpb7d3xUsersPeer::USER_REGDATE)) $criteria->add(Phpb7d3xUsersPeer::USER_REGDATE, $this->user_regdate);
		if ($this->isColumnModified(Phpb7d3xUsersPeer::USERNAME)) $criteria->add(Phpb7d3xUsersPeer::USERNAME, $this->username);
		if ($this->isColumnModified(Phpb7d3xUsersPeer::USERNAME_CLEAN)) $criteria->add(Phpb7d3xUsersPeer::USERNAME_CLEAN, $this->username_clean);
		if ($this->isColumnModified(Phpb7d3xUsersPeer::USER_PASSWORD)) $criteria->add(Phpb7d3xUsersPeer::USER_PASSWORD, $this->user_password);
		if ($this->isColumnModified(Phpb7d3xUsersPeer::USER_EMAIL)) $criteria->add(Phpb7d3xUsersPeer::USER_EMAIL, $this->user_email);
		if ($this->isColumnModified(Phpb7d3xUsersPeer::USER_EMAIL_HASH)) $criteria->add(Phpb7d3xUsersPeer::USER_EMAIL_HASH, $this->user_email_hash);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(Phpb7d3xUsersPeer::DATABASE_NAME);

		$criteria->add(Phpb7d3xUsersPeer::USER_ID, $this->user_id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getUserId();
	}

	/**
	 * Generic method to set the primary key (user_id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setUserId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Phpb7d3xUsers (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setUserType($this->user_type);

		$copyObj->setGroupId($this->group_id);

		$copyObj->setUserPermissions($this->user_permissions);

		$copyObj->setUserPermFrom($this->user_perm_from);

		$copyObj->setUserIp($this->user_ip);

		$copyObj->setUserRegdate($this->user_regdate);

		$copyObj->setUsername($this->username);

		$copyObj->setUsernameClean($this->username_clean);

		$copyObj->setUserPassword($this->user_password);

		$copyObj->setUserEmail($this->user_email);

		$copyObj->setUserEmailHash($this->user_email_hash);


		$copyObj->setNew(true);

		$copyObj->setUserId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Phpb7d3xUsers Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     Phpb7d3xUsersPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new Phpb7d3xUsersPeer();
		}
		return self::$peer;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BasePhpb7d3xUsers:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BasePhpb7d3xUsers::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BasePhpb7d3xUsers
