<?php

/**
 * Base class that represents a row from the 'photo' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri May  6 15:14:07 2011
 *
 * @package    lib.model.om
 */
abstract class BasePhoto extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        PhotoPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the photoalbum_id field.
	 * @var        int
	 */
	protected $photoalbum_id;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * The value for the show field.
	 * Note: this column has a database default value of: true
	 * @var        boolean
	 */
	protected $show;

	/**
	 * The value for the order field.
	 * @var        int
	 */
	protected $order;

	/**
	 * The value for the img field.
	 * @var        string
	 */
	protected $img;

	/**
	 * The value for the full_path field.
	 * @var        string
	 */
	protected $full_path;

	/**
	 * The value for the preview_path field.
	 * @var        string
	 */
	protected $preview_path;

	/**
	 * The value for the thumb_path field.
	 * @var        string
	 */
	protected $thumb_path;

	/**
	 * The value for the link field.
	 * @var        string
	 */
	protected $link;

	/**
	 * The value for the prev_img field.
	 * @var        string
	 */
	protected $prev_img;

	/**
	 * @var        Photoalbum
	 */
	protected $aPhotoalbum;

	/**
	 * @var        array PhotoI18n[] Collection to store aggregation of PhotoI18n objects.
	 */
	protected $collPhotoI18ns;

	/**
	 * @var        Criteria The criteria used to select the current contents of collPhotoI18ns.
	 */
	private $lastPhotoI18nCriteria = null;

	/**
	 * @var        array Photo2comments[] Collection to store aggregation of Photo2comments objects.
	 */
	protected $collPhoto2commentss;

	/**
	 * @var        Criteria The criteria used to select the current contents of collPhoto2commentss.
	 */
	private $lastPhoto2commentsCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'PhotoPeer';

	// symfony_i18n behavior
	
	/**
	 * @var string The value for the culture field
	 */
	protected $culture = null;
	
	/**
	 * @var array Current I18N objects
	 */
	protected $current_i18n = array();

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->show = true;
	}

	/**
	 * Initializes internal state of BasePhoto object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [photoalbum_id] column value.
	 * 
	 * @return     int
	 */
	public function getPhotoalbumId()
	{
		return $this->photoalbum_id;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [show] column value.
	 * 
	 * @return     boolean
	 */
	public function getShow()
	{
		return $this->show;
	}

	/**
	 * Get the [order] column value.
	 * 
	 * @return     int
	 */
	public function getOrder()
	{
		return $this->order;
	}

	/**
	 * Get the [img] column value.
	 * 
	 * @return     string
	 */
	public function getImg()
	{
		return $this->img;
	}

	/**
	 * Get the [full_path] column value.
	 * 
	 * @return     string
	 */
	public function getFullPath()
	{
		return $this->full_path;
	}

	/**
	 * Get the [preview_path] column value.
	 * 
	 * @return     string
	 */
	public function getPreviewPath()
	{
		return $this->preview_path;
	}

	/**
	 * Get the [thumb_path] column value.
	 * 
	 * @return     string
	 */
	public function getThumbPath()
	{
		return $this->thumb_path;
	}

	/**
	 * Get the [link] column value.
	 * 
	 * @return     string
	 */
	public function getLink()
	{
		return $this->link;
	}

	/**
	 * Get the [prev_img] column value.
	 * 
	 * @return     string
	 */
	public function getPrevImg()
	{
		return $this->prev_img;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Photo The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = PhotoPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [photoalbum_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Photo The current object (for fluent API support)
	 */
	public function setPhotoalbumId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->photoalbum_id !== $v) {
			$this->photoalbum_id = $v;
			$this->modifiedColumns[] = PhotoPeer::PHOTOALBUM_ID;
		}

		if ($this->aPhotoalbum !== null && $this->aPhotoalbum->getId() !== $v) {
			$this->aPhotoalbum = null;
		}

		return $this;
	} // setPhotoalbumId()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Photo The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = PhotoPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Photo The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = PhotoPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Set the value of [show] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Photo The current object (for fluent API support)
	 */
	public function setShow($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->show !== $v || $this->isNew()) {
			$this->show = $v;
			$this->modifiedColumns[] = PhotoPeer::SHOW;
		}

		return $this;
	} // setShow()

	/**
	 * Set the value of [order] column.
	 * 
	 * @param      int $v new value
	 * @return     Photo The current object (for fluent API support)
	 */
	public function setOrder($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->order !== $v) {
			$this->order = $v;
			$this->modifiedColumns[] = PhotoPeer::ORDER;
		}

		return $this;
	} // setOrder()

	/**
	 * Set the value of [img] column.
	 * 
	 * @param      string $v new value
	 * @return     Photo The current object (for fluent API support)
	 */
	public function setImg($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->img !== $v) {
			$this->img = $v;
			$this->modifiedColumns[] = PhotoPeer::IMG;
		}

		return $this;
	} // setImg()

	/**
	 * Set the value of [full_path] column.
	 * 
	 * @param      string $v new value
	 * @return     Photo The current object (for fluent API support)
	 */
	public function setFullPath($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->full_path !== $v) {
			$this->full_path = $v;
			$this->modifiedColumns[] = PhotoPeer::FULL_PATH;
		}

		return $this;
	} // setFullPath()

	/**
	 * Set the value of [preview_path] column.
	 * 
	 * @param      string $v new value
	 * @return     Photo The current object (for fluent API support)
	 */
	public function setPreviewPath($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->preview_path !== $v) {
			$this->preview_path = $v;
			$this->modifiedColumns[] = PhotoPeer::PREVIEW_PATH;
		}

		return $this;
	} // setPreviewPath()

	/**
	 * Set the value of [thumb_path] column.
	 * 
	 * @param      string $v new value
	 * @return     Photo The current object (for fluent API support)
	 */
	public function setThumbPath($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->thumb_path !== $v) {
			$this->thumb_path = $v;
			$this->modifiedColumns[] = PhotoPeer::THUMB_PATH;
		}

		return $this;
	} // setThumbPath()

	/**
	 * Set the value of [link] column.
	 * 
	 * @param      string $v new value
	 * @return     Photo The current object (for fluent API support)
	 */
	public function setLink($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->link !== $v) {
			$this->link = $v;
			$this->modifiedColumns[] = PhotoPeer::LINK;
		}

		return $this;
	} // setLink()

	/**
	 * Set the value of [prev_img] column.
	 * 
	 * @param      string $v new value
	 * @return     Photo The current object (for fluent API support)
	 */
	public function setPrevImg($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->prev_img !== $v) {
			$this->prev_img = $v;
			$this->modifiedColumns[] = PhotoPeer::PREV_IMG;
		}

		return $this;
	} // setPrevImg()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			if ($this->show !== true) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->photoalbum_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->created_at = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->updated_at = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->show = ($row[$startcol + 4] !== null) ? (boolean) $row[$startcol + 4] : null;
			$this->order = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->img = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->full_path = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->preview_path = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->thumb_path = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->link = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->prev_img = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 12; // 12 = PhotoPeer::NUM_COLUMNS - PhotoPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Photo object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aPhotoalbum !== null && $this->photoalbum_id !== $this->aPhotoalbum->getId()) {
			$this->aPhotoalbum = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PhotoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = PhotoPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aPhotoalbum = null;
			$this->collPhotoI18ns = null;
			$this->lastPhotoI18nCriteria = null;

			$this->collPhoto2commentss = null;
			$this->lastPhoto2commentsCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PhotoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BasePhoto:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				PhotoPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BasePhoto:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PhotoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BasePhoto:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			// symfony_timestampable behavior
			if ($this->isModified() && !$this->isColumnModified(PhotoPeer::UPDATED_AT))
			{
			  $this->setUpdatedAt(time());
			}
			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// symfony_timestampable behavior
				if (!$this->isColumnModified(PhotoPeer::CREATED_AT))
				{
				  $this->setCreatedAt(time());
				}

			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BasePhoto:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				PhotoPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aPhotoalbum !== null) {
				if ($this->aPhotoalbum->isModified() || $this->aPhotoalbum->isNew()) {
					$affectedRows += $this->aPhotoalbum->save($con);
				}
				$this->setPhotoalbum($this->aPhotoalbum);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = PhotoPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = PhotoPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += PhotoPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collPhotoI18ns !== null) {
				foreach ($this->collPhotoI18ns as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collPhoto2commentss !== null) {
				foreach ($this->collPhoto2commentss as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aPhotoalbum !== null) {
				if (!$this->aPhotoalbum->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aPhotoalbum->getValidationFailures());
				}
			}


			if (($retval = PhotoPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collPhotoI18ns !== null) {
					foreach ($this->collPhotoI18ns as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collPhoto2commentss !== null) {
					foreach ($this->collPhoto2commentss as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = PhotoPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getPhotoalbumId();
				break;
			case 2:
				return $this->getCreatedAt();
				break;
			case 3:
				return $this->getUpdatedAt();
				break;
			case 4:
				return $this->getShow();
				break;
			case 5:
				return $this->getOrder();
				break;
			case 6:
				return $this->getImg();
				break;
			case 7:
				return $this->getFullPath();
				break;
			case 8:
				return $this->getPreviewPath();
				break;
			case 9:
				return $this->getThumbPath();
				break;
			case 10:
				return $this->getLink();
				break;
			case 11:
				return $this->getPrevImg();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = PhotoPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getPhotoalbumId(),
			$keys[2] => $this->getCreatedAt(),
			$keys[3] => $this->getUpdatedAt(),
			$keys[4] => $this->getShow(),
			$keys[5] => $this->getOrder(),
			$keys[6] => $this->getImg(),
			$keys[7] => $this->getFullPath(),
			$keys[8] => $this->getPreviewPath(),
			$keys[9] => $this->getThumbPath(),
			$keys[10] => $this->getLink(),
			$keys[11] => $this->getPrevImg(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = PhotoPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setPhotoalbumId($value);
				break;
			case 2:
				$this->setCreatedAt($value);
				break;
			case 3:
				$this->setUpdatedAt($value);
				break;
			case 4:
				$this->setShow($value);
				break;
			case 5:
				$this->setOrder($value);
				break;
			case 6:
				$this->setImg($value);
				break;
			case 7:
				$this->setFullPath($value);
				break;
			case 8:
				$this->setPreviewPath($value);
				break;
			case 9:
				$this->setThumbPath($value);
				break;
			case 10:
				$this->setLink($value);
				break;
			case 11:
				$this->setPrevImg($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = PhotoPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setPhotoalbumId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setCreatedAt($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setUpdatedAt($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setShow($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setOrder($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setImg($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setFullPath($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setPreviewPath($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setThumbPath($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setLink($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setPrevImg($arr[$keys[11]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(PhotoPeer::DATABASE_NAME);

		if ($this->isColumnModified(PhotoPeer::ID)) $criteria->add(PhotoPeer::ID, $this->id);
		if ($this->isColumnModified(PhotoPeer::PHOTOALBUM_ID)) $criteria->add(PhotoPeer::PHOTOALBUM_ID, $this->photoalbum_id);
		if ($this->isColumnModified(PhotoPeer::CREATED_AT)) $criteria->add(PhotoPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(PhotoPeer::UPDATED_AT)) $criteria->add(PhotoPeer::UPDATED_AT, $this->updated_at);
		if ($this->isColumnModified(PhotoPeer::SHOW)) $criteria->add(PhotoPeer::SHOW, $this->show);
		if ($this->isColumnModified(PhotoPeer::ORDER)) $criteria->add(PhotoPeer::ORDER, $this->order);
		if ($this->isColumnModified(PhotoPeer::IMG)) $criteria->add(PhotoPeer::IMG, $this->img);
		if ($this->isColumnModified(PhotoPeer::FULL_PATH)) $criteria->add(PhotoPeer::FULL_PATH, $this->full_path);
		if ($this->isColumnModified(PhotoPeer::PREVIEW_PATH)) $criteria->add(PhotoPeer::PREVIEW_PATH, $this->preview_path);
		if ($this->isColumnModified(PhotoPeer::THUMB_PATH)) $criteria->add(PhotoPeer::THUMB_PATH, $this->thumb_path);
		if ($this->isColumnModified(PhotoPeer::LINK)) $criteria->add(PhotoPeer::LINK, $this->link);
		if ($this->isColumnModified(PhotoPeer::PREV_IMG)) $criteria->add(PhotoPeer::PREV_IMG, $this->prev_img);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(PhotoPeer::DATABASE_NAME);

		$criteria->add(PhotoPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Photo (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setPhotoalbumId($this->photoalbum_id);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);

		$copyObj->setShow($this->show);

		$copyObj->setOrder($this->order);

		$copyObj->setImg($this->img);

		$copyObj->setFullPath($this->full_path);

		$copyObj->setPreviewPath($this->preview_path);

		$copyObj->setThumbPath($this->thumb_path);

		$copyObj->setLink($this->link);

		$copyObj->setPrevImg($this->prev_img);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getPhotoI18ns() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addPhotoI18n($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getPhoto2commentss() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addPhoto2comments($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Photo Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     PhotoPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new PhotoPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Photoalbum object.
	 *
	 * @param      Photoalbum $v
	 * @return     Photo The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setPhotoalbum(Photoalbum $v = null)
	{
		if ($v === null) {
			$this->setPhotoalbumId(NULL);
		} else {
			$this->setPhotoalbumId($v->getId());
		}

		$this->aPhotoalbum = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Photoalbum object, it will not be re-added.
		if ($v !== null) {
			$v->addPhoto($this);
		}

		return $this;
	}


	/**
	 * Get the associated Photoalbum object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Photoalbum The associated Photoalbum object.
	 * @throws     PropelException
	 */
	public function getPhotoalbum(PropelPDO $con = null)
	{
		if ($this->aPhotoalbum === null && ($this->photoalbum_id !== null)) {
			$this->aPhotoalbum = PhotoalbumPeer::retrieveByPk($this->photoalbum_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aPhotoalbum->addPhotos($this);
			 */
		}
		return $this->aPhotoalbum;
	}

	/**
	 * Clears out the collPhotoI18ns collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addPhotoI18ns()
	 */
	public function clearPhotoI18ns()
	{
		$this->collPhotoI18ns = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collPhotoI18ns collection (array).
	 *
	 * By default this just sets the collPhotoI18ns collection to an empty array (like clearcollPhotoI18ns());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initPhotoI18ns()
	{
		$this->collPhotoI18ns = array();
	}

	/**
	 * Gets an array of PhotoI18n objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Photo has previously been saved, it will retrieve
	 * related PhotoI18ns from storage. If this Photo is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array PhotoI18n[]
	 * @throws     PropelException
	 */
	public function getPhotoI18ns($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PhotoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPhotoI18ns === null) {
			if ($this->isNew()) {
			   $this->collPhotoI18ns = array();
			} else {

				$criteria->add(PhotoI18nPeer::ID, $this->id);

				PhotoI18nPeer::addSelectColumns($criteria);
				$this->collPhotoI18ns = PhotoI18nPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(PhotoI18nPeer::ID, $this->id);

				PhotoI18nPeer::addSelectColumns($criteria);
				if (!isset($this->lastPhotoI18nCriteria) || !$this->lastPhotoI18nCriteria->equals($criteria)) {
					$this->collPhotoI18ns = PhotoI18nPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastPhotoI18nCriteria = $criteria;
		return $this->collPhotoI18ns;
	}

	/**
	 * Returns the number of related PhotoI18n objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related PhotoI18n objects.
	 * @throws     PropelException
	 */
	public function countPhotoI18ns(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PhotoPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collPhotoI18ns === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(PhotoI18nPeer::ID, $this->id);

				$count = PhotoI18nPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(PhotoI18nPeer::ID, $this->id);

				if (!isset($this->lastPhotoI18nCriteria) || !$this->lastPhotoI18nCriteria->equals($criteria)) {
					$count = PhotoI18nPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collPhotoI18ns);
				}
			} else {
				$count = count($this->collPhotoI18ns);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a PhotoI18n object to this object
	 * through the PhotoI18n foreign key attribute.
	 *
	 * @param      PhotoI18n $l PhotoI18n
	 * @return     void
	 * @throws     PropelException
	 */
	public function addPhotoI18n(PhotoI18n $l)
	{
		if ($this->collPhotoI18ns === null) {
			$this->initPhotoI18ns();
		}
		if (!in_array($l, $this->collPhotoI18ns, true)) { // only add it if the **same** object is not already associated
			array_push($this->collPhotoI18ns, $l);
			$l->setPhoto($this);
		}
	}

	/**
	 * Clears out the collPhoto2commentss collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addPhoto2commentss()
	 */
	public function clearPhoto2commentss()
	{
		$this->collPhoto2commentss = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collPhoto2commentss collection (array).
	 *
	 * By default this just sets the collPhoto2commentss collection to an empty array (like clearcollPhoto2commentss());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initPhoto2commentss()
	{
		$this->collPhoto2commentss = array();
	}

	/**
	 * Gets an array of Photo2comments objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Photo has previously been saved, it will retrieve
	 * related Photo2commentss from storage. If this Photo is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Photo2comments[]
	 * @throws     PropelException
	 */
	public function getPhoto2commentss($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PhotoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPhoto2commentss === null) {
			if ($this->isNew()) {
			   $this->collPhoto2commentss = array();
			} else {

				$criteria->add(Photo2commentsPeer::PHOTO_ID, $this->id);

				Photo2commentsPeer::addSelectColumns($criteria);
				$this->collPhoto2commentss = Photo2commentsPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(Photo2commentsPeer::PHOTO_ID, $this->id);

				Photo2commentsPeer::addSelectColumns($criteria);
				if (!isset($this->lastPhoto2commentsCriteria) || !$this->lastPhoto2commentsCriteria->equals($criteria)) {
					$this->collPhoto2commentss = Photo2commentsPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastPhoto2commentsCriteria = $criteria;
		return $this->collPhoto2commentss;
	}

	/**
	 * Returns the number of related Photo2comments objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Photo2comments objects.
	 * @throws     PropelException
	 */
	public function countPhoto2commentss(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PhotoPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collPhoto2commentss === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(Photo2commentsPeer::PHOTO_ID, $this->id);

				$count = Photo2commentsPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(Photo2commentsPeer::PHOTO_ID, $this->id);

				if (!isset($this->lastPhoto2commentsCriteria) || !$this->lastPhoto2commentsCriteria->equals($criteria)) {
					$count = Photo2commentsPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collPhoto2commentss);
				}
			} else {
				$count = count($this->collPhoto2commentss);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Photo2comments object to this object
	 * through the Photo2comments foreign key attribute.
	 *
	 * @param      Photo2comments $l Photo2comments
	 * @return     void
	 * @throws     PropelException
	 */
	public function addPhoto2comments(Photo2comments $l)
	{
		if ($this->collPhoto2commentss === null) {
			$this->initPhoto2commentss();
		}
		if (!in_array($l, $this->collPhoto2commentss, true)) { // only add it if the **same** object is not already associated
			array_push($this->collPhoto2commentss, $l);
			$l->setPhoto($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Photo is new, it will return
	 * an empty collection; or if this Photo has previously
	 * been saved, it will retrieve related Photo2commentss from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Photo.
	 */
	public function getPhoto2commentssJoinComments($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PhotoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPhoto2commentss === null) {
			if ($this->isNew()) {
				$this->collPhoto2commentss = array();
			} else {

				$criteria->add(Photo2commentsPeer::PHOTO_ID, $this->id);

				$this->collPhoto2commentss = Photo2commentsPeer::doSelectJoinComments($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(Photo2commentsPeer::PHOTO_ID, $this->id);

			if (!isset($this->lastPhoto2commentsCriteria) || !$this->lastPhoto2commentsCriteria->equals($criteria)) {
				$this->collPhoto2commentss = Photo2commentsPeer::doSelectJoinComments($criteria, $con, $join_behavior);
			}
		}
		$this->lastPhoto2commentsCriteria = $criteria;

		return $this->collPhoto2commentss;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collPhotoI18ns) {
				foreach ((array) $this->collPhotoI18ns as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collPhoto2commentss) {
				foreach ((array) $this->collPhoto2commentss as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collPhotoI18ns = null;
		$this->collPhoto2commentss = null;
			$this->aPhotoalbum = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BasePhoto:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BasePhoto::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

	// symfony_i18n behavior
	
	/**
	 * Returns the culture.
	 *
	 * @return string The culture
	 */
	public function getCulture()
	{
	  return $this->culture;
	}
	
	/**
	 * Sets the culture.
	 *
	 * @param string  The culture to set
	 *
	 * @return Photo
	 */
	public function setCulture($culture)
	{
	  $this->culture = $culture;
	  return $this;
	}
	
	/**
	 * Returns the "updated_at_extra" value from the current {@link PhotoI18n}.
	 */
	public function getUpdatedAtExtra($culture = null)
	{
	  return $this->getCurrentPhotoI18n($culture)->getUpdatedAtExtra();
	}
	
	/**
	 * Sets the "updated_at_extra" value of the current {@link PhotoI18n}.
	 *
	 * @return Photo
	 */
	public function setUpdatedAtExtra($value, $culture = null)
	{
	  $this->getCurrentPhotoI18n($culture)->setUpdatedAtExtra($value);
	  return $this;
	}
	
	/**
	 * Returns the "title" value from the current {@link PhotoI18n}.
	 */
	public function getTitle($culture = null)
	{
	  return $this->getCurrentPhotoI18n($culture)->getTitle();
	}
	
	/**
	 * Sets the "title" value of the current {@link PhotoI18n}.
	 *
	 * @return Photo
	 */
	public function setTitle($value, $culture = null)
	{
	  $this->getCurrentPhotoI18n($culture)->setTitle($value);
	  return $this;
	}
	
	/**
	 * Returns the "body" value from the current {@link PhotoI18n}.
	 */
	public function getBody($culture = null)
	{
	  return $this->getCurrentPhotoI18n($culture)->getBody();
	}
	
	/**
	 * Sets the "body" value of the current {@link PhotoI18n}.
	 *
	 * @return Photo
	 */
	public function setBody($value, $culture = null)
	{
	  $this->getCurrentPhotoI18n($culture)->setBody($value);
	  return $this;
	}
	
	/**
	 * Returns the "author" value from the current {@link PhotoI18n}.
	 */
	public function getAuthor($culture = null)
	{
	  return $this->getCurrentPhotoI18n($culture)->getAuthor();
	}
	
	/**
	 * Sets the "author" value of the current {@link PhotoI18n}.
	 *
	 * @return Photo
	 */
	public function setAuthor($value, $culture = null)
	{
	  $this->getCurrentPhotoI18n($culture)->setAuthor($value);
	  return $this;
	}
	
	/**
	 * Returns the current translation.
	 *
	 * @return PhotoI18n
	 */
	public function getCurrentPhotoI18n($culture = null)
	{
	  if (null === $culture)
	  {
	    $culture = null === $this->culture ? sfPropel::getDefaultCulture() : $this->culture;
	  }
	
	  if (!isset($this->current_i18n[$culture]))
	  {
	    $object = $this->isNew() ? null : PhotoI18nPeer::retrieveByPK($this->getPrimaryKey(), $culture);
	    if ($object)
	    {
	      $this->setPhotoI18nForCulture($object, $culture);
	    }
	    else
	    {
	      $this->setPhotoI18nForCulture(new PhotoI18n(), $culture);
	      $this->current_i18n[$culture]->setCulture($culture);
	    }
	  }
	
	  return $this->current_i18n[$culture];
	}
	
	/**
	 * Sets the translation object for a culture.
	 */
	public function setPhotoI18nForCulture(PhotoI18n $object, $culture)
	{
	  $this->current_i18n[$culture] = $object;
	  $this->addPhotoI18n($object);
	}

} // BasePhoto
