<?php

/**
 * Base class that represents a row from the 'phpb7d3x_sessions' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Mar 14 05:57:47 2011
 *
 * @package    lib.model.om
 */
abstract class BasePhpb7d3xSessions extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        Phpb7d3xSessionsPeer
	 */
	protected static $peer;

	/**
	 * The value for the session_id field.
	 * @var        string
	 */
	protected $session_id;

	/**
	 * The value for the session_user_id field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $session_user_id;

	/**
	 * The value for the session_forum_id field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $session_forum_id;

	/**
	 * The value for the session_last_visit field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $session_last_visit;

	/**
	 * The value for the session_start field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $session_start;

	/**
	 * The value for the session_time field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $session_time;

	/**
	 * The value for the session_ip field.
	 * Note: this column has a database default value of: ''
	 * @var        string
	 */
	protected $session_ip;

	/**
	 * The value for the session_browser field.
	 * Note: this column has a database default value of: ''
	 * @var        string
	 */
	protected $session_browser;

	/**
	 * The value for the session_forwarded_for field.
	 * Note: this column has a database default value of: ''
	 * @var        string
	 */
	protected $session_forwarded_for;

	/**
	 * The value for the session_page field.
	 * Note: this column has a database default value of: ''
	 * @var        string
	 */
	protected $session_page;

	/**
	 * The value for the session_viewonline field.
	 * Note: this column has a database default value of: 1
	 * @var        int
	 */
	protected $session_viewonline;

	/**
	 * The value for the session_autologin field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $session_autologin;

	/**
	 * The value for the session_admin field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $session_admin;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'Phpb7d3xSessionsPeer';

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->session_user_id = 0;
		$this->session_forum_id = 0;
		$this->session_last_visit = 0;
		$this->session_start = 0;
		$this->session_time = 0;
		$this->session_ip = '';
		$this->session_browser = '';
		$this->session_forwarded_for = '';
		$this->session_page = '';
		$this->session_viewonline = 1;
		$this->session_autologin = 0;
		$this->session_admin = 0;
	}

	/**
	 * Initializes internal state of BasePhpb7d3xSessions object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Get the [session_id] column value.
	 * 
	 * @return     string
	 */
	public function getSessionId()
	{
		return $this->session_id;
	}

	/**
	 * Get the [session_user_id] column value.
	 * 
	 * @return     int
	 */
	public function getSessionUserId()
	{
		return $this->session_user_id;
	}

	/**
	 * Get the [session_forum_id] column value.
	 * 
	 * @return     int
	 */
	public function getSessionForumId()
	{
		return $this->session_forum_id;
	}

	/**
	 * Get the [session_last_visit] column value.
	 * 
	 * @return     int
	 */
	public function getSessionLastVisit()
	{
		return $this->session_last_visit;
	}

	/**
	 * Get the [session_start] column value.
	 * 
	 * @return     int
	 */
	public function getSessionStart()
	{
		return $this->session_start;
	}

	/**
	 * Get the [session_time] column value.
	 * 
	 * @return     int
	 */
	public function getSessionTime()
	{
		return $this->session_time;
	}

	/**
	 * Get the [session_ip] column value.
	 * 
	 * @return     string
	 */
	public function getSessionIp()
	{
		return $this->session_ip;
	}

	/**
	 * Get the [session_browser] column value.
	 * 
	 * @return     string
	 */
	public function getSessionBrowser()
	{
		return $this->session_browser;
	}

	/**
	 * Get the [session_forwarded_for] column value.
	 * 
	 * @return     string
	 */
	public function getSessionForwardedFor()
	{
		return $this->session_forwarded_for;
	}

	/**
	 * Get the [session_page] column value.
	 * 
	 * @return     string
	 */
	public function getSessionPage()
	{
		return $this->session_page;
	}

	/**
	 * Get the [session_viewonline] column value.
	 * 
	 * @return     int
	 */
	public function getSessionViewonline()
	{
		return $this->session_viewonline;
	}

	/**
	 * Get the [session_autologin] column value.
	 * 
	 * @return     int
	 */
	public function getSessionAutologin()
	{
		return $this->session_autologin;
	}

	/**
	 * Get the [session_admin] column value.
	 * 
	 * @return     int
	 */
	public function getSessionAdmin()
	{
		return $this->session_admin;
	}

	/**
	 * Set the value of [session_id] column.
	 * 
	 * @param      string $v new value
	 * @return     Phpb7d3xSessions The current object (for fluent API support)
	 */
	public function setSessionId($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->session_id !== $v) {
			$this->session_id = $v;
			$this->modifiedColumns[] = Phpb7d3xSessionsPeer::SESSION_ID;
		}

		return $this;
	} // setSessionId()

	/**
	 * Set the value of [session_user_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Phpb7d3xSessions The current object (for fluent API support)
	 */
	public function setSessionUserId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->session_user_id !== $v || $this->isNew()) {
			$this->session_user_id = $v;
			$this->modifiedColumns[] = Phpb7d3xSessionsPeer::SESSION_USER_ID;
		}

		return $this;
	} // setSessionUserId()

	/**
	 * Set the value of [session_forum_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Phpb7d3xSessions The current object (for fluent API support)
	 */
	public function setSessionForumId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->session_forum_id !== $v || $this->isNew()) {
			$this->session_forum_id = $v;
			$this->modifiedColumns[] = Phpb7d3xSessionsPeer::SESSION_FORUM_ID;
		}

		return $this;
	} // setSessionForumId()

	/**
	 * Set the value of [session_last_visit] column.
	 * 
	 * @param      int $v new value
	 * @return     Phpb7d3xSessions The current object (for fluent API support)
	 */
	public function setSessionLastVisit($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->session_last_visit !== $v || $this->isNew()) {
			$this->session_last_visit = $v;
			$this->modifiedColumns[] = Phpb7d3xSessionsPeer::SESSION_LAST_VISIT;
		}

		return $this;
	} // setSessionLastVisit()

	/**
	 * Set the value of [session_start] column.
	 * 
	 * @param      int $v new value
	 * @return     Phpb7d3xSessions The current object (for fluent API support)
	 */
	public function setSessionStart($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->session_start !== $v || $this->isNew()) {
			$this->session_start = $v;
			$this->modifiedColumns[] = Phpb7d3xSessionsPeer::SESSION_START;
		}

		return $this;
	} // setSessionStart()

	/**
	 * Set the value of [session_time] column.
	 * 
	 * @param      int $v new value
	 * @return     Phpb7d3xSessions The current object (for fluent API support)
	 */
	public function setSessionTime($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->session_time !== $v || $this->isNew()) {
			$this->session_time = $v;
			$this->modifiedColumns[] = Phpb7d3xSessionsPeer::SESSION_TIME;
		}

		return $this;
	} // setSessionTime()

	/**
	 * Set the value of [session_ip] column.
	 * 
	 * @param      string $v new value
	 * @return     Phpb7d3xSessions The current object (for fluent API support)
	 */
	public function setSessionIp($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->session_ip !== $v || $this->isNew()) {
			$this->session_ip = $v;
			$this->modifiedColumns[] = Phpb7d3xSessionsPeer::SESSION_IP;
		}

		return $this;
	} // setSessionIp()

	/**
	 * Set the value of [session_browser] column.
	 * 
	 * @param      string $v new value
	 * @return     Phpb7d3xSessions The current object (for fluent API support)
	 */
	public function setSessionBrowser($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->session_browser !== $v || $this->isNew()) {
			$this->session_browser = $v;
			$this->modifiedColumns[] = Phpb7d3xSessionsPeer::SESSION_BROWSER;
		}

		return $this;
	} // setSessionBrowser()

	/**
	 * Set the value of [session_forwarded_for] column.
	 * 
	 * @param      string $v new value
	 * @return     Phpb7d3xSessions The current object (for fluent API support)
	 */
	public function setSessionForwardedFor($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->session_forwarded_for !== $v || $this->isNew()) {
			$this->session_forwarded_for = $v;
			$this->modifiedColumns[] = Phpb7d3xSessionsPeer::SESSION_FORWARDED_FOR;
		}

		return $this;
	} // setSessionForwardedFor()

	/**
	 * Set the value of [session_page] column.
	 * 
	 * @param      string $v new value
	 * @return     Phpb7d3xSessions The current object (for fluent API support)
	 */
	public function setSessionPage($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->session_page !== $v || $this->isNew()) {
			$this->session_page = $v;
			$this->modifiedColumns[] = Phpb7d3xSessionsPeer::SESSION_PAGE;
		}

		return $this;
	} // setSessionPage()

	/**
	 * Set the value of [session_viewonline] column.
	 * 
	 * @param      int $v new value
	 * @return     Phpb7d3xSessions The current object (for fluent API support)
	 */
	public function setSessionViewonline($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->session_viewonline !== $v || $this->isNew()) {
			$this->session_viewonline = $v;
			$this->modifiedColumns[] = Phpb7d3xSessionsPeer::SESSION_VIEWONLINE;
		}

		return $this;
	} // setSessionViewonline()

	/**
	 * Set the value of [session_autologin] column.
	 * 
	 * @param      int $v new value
	 * @return     Phpb7d3xSessions The current object (for fluent API support)
	 */
	public function setSessionAutologin($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->session_autologin !== $v || $this->isNew()) {
			$this->session_autologin = $v;
			$this->modifiedColumns[] = Phpb7d3xSessionsPeer::SESSION_AUTOLOGIN;
		}

		return $this;
	} // setSessionAutologin()

	/**
	 * Set the value of [session_admin] column.
	 * 
	 * @param      int $v new value
	 * @return     Phpb7d3xSessions The current object (for fluent API support)
	 */
	public function setSessionAdmin($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->session_admin !== $v || $this->isNew()) {
			$this->session_admin = $v;
			$this->modifiedColumns[] = Phpb7d3xSessionsPeer::SESSION_ADMIN;
		}

		return $this;
	} // setSessionAdmin()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			if ($this->session_user_id !== 0) {
				return false;
			}

			if ($this->session_forum_id !== 0) {
				return false;
			}

			if ($this->session_last_visit !== 0) {
				return false;
			}

			if ($this->session_start !== 0) {
				return false;
			}

			if ($this->session_time !== 0) {
				return false;
			}

			if ($this->session_ip !== '') {
				return false;
			}

			if ($this->session_browser !== '') {
				return false;
			}

			if ($this->session_forwarded_for !== '') {
				return false;
			}

			if ($this->session_page !== '') {
				return false;
			}

			if ($this->session_viewonline !== 1) {
				return false;
			}

			if ($this->session_autologin !== 0) {
				return false;
			}

			if ($this->session_admin !== 0) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->session_id = ($row[$startcol + 0] !== null) ? (string) $row[$startcol + 0] : null;
			$this->session_user_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->session_forum_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->session_last_visit = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->session_start = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->session_time = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->session_ip = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->session_browser = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->session_forwarded_for = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->session_page = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->session_viewonline = ($row[$startcol + 10] !== null) ? (int) $row[$startcol + 10] : null;
			$this->session_autologin = ($row[$startcol + 11] !== null) ? (int) $row[$startcol + 11] : null;
			$this->session_admin = ($row[$startcol + 12] !== null) ? (int) $row[$startcol + 12] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 13; // 13 = Phpb7d3xSessionsPeer::NUM_COLUMNS - Phpb7d3xSessionsPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Phpb7d3xSessions object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(Phpb7d3xSessionsPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = Phpb7d3xSessionsPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(Phpb7d3xSessionsPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BasePhpb7d3xSessions:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				Phpb7d3xSessionsPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BasePhpb7d3xSessions:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(Phpb7d3xSessionsPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BasePhpb7d3xSessions:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BasePhpb7d3xSessions:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				Phpb7d3xSessionsPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;


			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = Phpb7d3xSessionsPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setNew(false);
				} else {
					$affectedRows += Phpb7d3xSessionsPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = Phpb7d3xSessionsPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = Phpb7d3xSessionsPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getSessionId();
				break;
			case 1:
				return $this->getSessionUserId();
				break;
			case 2:
				return $this->getSessionForumId();
				break;
			case 3:
				return $this->getSessionLastVisit();
				break;
			case 4:
				return $this->getSessionStart();
				break;
			case 5:
				return $this->getSessionTime();
				break;
			case 6:
				return $this->getSessionIp();
				break;
			case 7:
				return $this->getSessionBrowser();
				break;
			case 8:
				return $this->getSessionForwardedFor();
				break;
			case 9:
				return $this->getSessionPage();
				break;
			case 10:
				return $this->getSessionViewonline();
				break;
			case 11:
				return $this->getSessionAutologin();
				break;
			case 12:
				return $this->getSessionAdmin();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = Phpb7d3xSessionsPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getSessionId(),
			$keys[1] => $this->getSessionUserId(),
			$keys[2] => $this->getSessionForumId(),
			$keys[3] => $this->getSessionLastVisit(),
			$keys[4] => $this->getSessionStart(),
			$keys[5] => $this->getSessionTime(),
			$keys[6] => $this->getSessionIp(),
			$keys[7] => $this->getSessionBrowser(),
			$keys[8] => $this->getSessionForwardedFor(),
			$keys[9] => $this->getSessionPage(),
			$keys[10] => $this->getSessionViewonline(),
			$keys[11] => $this->getSessionAutologin(),
			$keys[12] => $this->getSessionAdmin(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = Phpb7d3xSessionsPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setSessionId($value);
				break;
			case 1:
				$this->setSessionUserId($value);
				break;
			case 2:
				$this->setSessionForumId($value);
				break;
			case 3:
				$this->setSessionLastVisit($value);
				break;
			case 4:
				$this->setSessionStart($value);
				break;
			case 5:
				$this->setSessionTime($value);
				break;
			case 6:
				$this->setSessionIp($value);
				break;
			case 7:
				$this->setSessionBrowser($value);
				break;
			case 8:
				$this->setSessionForwardedFor($value);
				break;
			case 9:
				$this->setSessionPage($value);
				break;
			case 10:
				$this->setSessionViewonline($value);
				break;
			case 11:
				$this->setSessionAutologin($value);
				break;
			case 12:
				$this->setSessionAdmin($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = Phpb7d3xSessionsPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setSessionId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setSessionUserId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setSessionForumId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setSessionLastVisit($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setSessionStart($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setSessionTime($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setSessionIp($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setSessionBrowser($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setSessionForwardedFor($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setSessionPage($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setSessionViewonline($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setSessionAutologin($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setSessionAdmin($arr[$keys[12]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(Phpb7d3xSessionsPeer::DATABASE_NAME);

		if ($this->isColumnModified(Phpb7d3xSessionsPeer::SESSION_ID)) $criteria->add(Phpb7d3xSessionsPeer::SESSION_ID, $this->session_id);
		if ($this->isColumnModified(Phpb7d3xSessionsPeer::SESSION_USER_ID)) $criteria->add(Phpb7d3xSessionsPeer::SESSION_USER_ID, $this->session_user_id);
		if ($this->isColumnModified(Phpb7d3xSessionsPeer::SESSION_FORUM_ID)) $criteria->add(Phpb7d3xSessionsPeer::SESSION_FORUM_ID, $this->session_forum_id);
		if ($this->isColumnModified(Phpb7d3xSessionsPeer::SESSION_LAST_VISIT)) $criteria->add(Phpb7d3xSessionsPeer::SESSION_LAST_VISIT, $this->session_last_visit);
		if ($this->isColumnModified(Phpb7d3xSessionsPeer::SESSION_START)) $criteria->add(Phpb7d3xSessionsPeer::SESSION_START, $this->session_start);
		if ($this->isColumnModified(Phpb7d3xSessionsPeer::SESSION_TIME)) $criteria->add(Phpb7d3xSessionsPeer::SESSION_TIME, $this->session_time);
		if ($this->isColumnModified(Phpb7d3xSessionsPeer::SESSION_IP)) $criteria->add(Phpb7d3xSessionsPeer::SESSION_IP, $this->session_ip);
		if ($this->isColumnModified(Phpb7d3xSessionsPeer::SESSION_BROWSER)) $criteria->add(Phpb7d3xSessionsPeer::SESSION_BROWSER, $this->session_browser);
		if ($this->isColumnModified(Phpb7d3xSessionsPeer::SESSION_FORWARDED_FOR)) $criteria->add(Phpb7d3xSessionsPeer::SESSION_FORWARDED_FOR, $this->session_forwarded_for);
		if ($this->isColumnModified(Phpb7d3xSessionsPeer::SESSION_PAGE)) $criteria->add(Phpb7d3xSessionsPeer::SESSION_PAGE, $this->session_page);
		if ($this->isColumnModified(Phpb7d3xSessionsPeer::SESSION_VIEWONLINE)) $criteria->add(Phpb7d3xSessionsPeer::SESSION_VIEWONLINE, $this->session_viewonline);
		if ($this->isColumnModified(Phpb7d3xSessionsPeer::SESSION_AUTOLOGIN)) $criteria->add(Phpb7d3xSessionsPeer::SESSION_AUTOLOGIN, $this->session_autologin);
		if ($this->isColumnModified(Phpb7d3xSessionsPeer::SESSION_ADMIN)) $criteria->add(Phpb7d3xSessionsPeer::SESSION_ADMIN, $this->session_admin);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(Phpb7d3xSessionsPeer::DATABASE_NAME);

		$criteria->add(Phpb7d3xSessionsPeer::SESSION_ID, $this->session_id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     string
	 */
	public function getPrimaryKey()
	{
		return $this->getSessionId();
	}

	/**
	 * Generic method to set the primary key (session_id column).
	 *
	 * @param      string $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setSessionId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Phpb7d3xSessions (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setSessionId($this->session_id);

		$copyObj->setSessionUserId($this->session_user_id);

		$copyObj->setSessionForumId($this->session_forum_id);

		$copyObj->setSessionLastVisit($this->session_last_visit);

		$copyObj->setSessionStart($this->session_start);

		$copyObj->setSessionTime($this->session_time);

		$copyObj->setSessionIp($this->session_ip);

		$copyObj->setSessionBrowser($this->session_browser);

		$copyObj->setSessionForwardedFor($this->session_forwarded_for);

		$copyObj->setSessionPage($this->session_page);

		$copyObj->setSessionViewonline($this->session_viewonline);

		$copyObj->setSessionAutologin($this->session_autologin);

		$copyObj->setSessionAdmin($this->session_admin);


		$copyObj->setNew(true);

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Phpb7d3xSessions Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     Phpb7d3xSessionsPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new Phpb7d3xSessionsPeer();
		}
		return self::$peer;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BasePhpb7d3xSessions:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BasePhpb7d3xSessions::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BasePhpb7d3xSessions
