#!/usr/local/php5/bin/php
<?php
// #!/home/say10okt/etapasvi.com/www/cgi-bin/php-wrapper-s3r.fcgi
/*
  #!/usr/bin/env php
 * This file is part of the symfony package.
 * (c) Fabien Potencier <fabien.potencier@symfony-project.com>
 * 
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

chdir(dirname(__FILE__));
require_once(dirname(__FILE__).'/config/ProjectConfiguration.class.php');
include(sfCoreAutoload::getInstance()->getBaseDir().'/command/cli.php');
