albums:
  enabled:     true

album:
  enabled:     true
  
index:
  enabled:     true

#_showwrapper:
#  enabled:     true

show:
  enabled:     true

content:
  enabled:     true

#_show:
#  enabled:     true