default:
  http_metas:
    content-type: text/html

  metas:
    title:        eTapasvi
    description:  Maha Sambodhi Dharma Sangha: Teachings, News, Photo, Video, Audio, Biography.

    #keywords:     symfony, project
    #language:     en, ru
    #robots:       index, follow


#  stylesheets:    [/css/css.css]
#  javascripts:    [http://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js, /js/js.js]

  has_layout:     true
  layout:         layout
