generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      News2comments
    theme:            default

    list:
      display: [news_id, comments_id, _comment_text]
      filters:  [news_id]
      sort: [comments_id, desc]
      object_actions:
        _edit:  ~
        _delete: ~