generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Item2item
    theme:            default
    
    list:
      max_per_page: 10000
      filters:  [item1_type, item2_type]
      sort: [id, desc]
      display: [_item1_type, item1_id, _item1_title, _item2_type, item2_id, _item2_title]
      object_actions:
        _edit:  ~
        _delete: ~
     