dev:
  propel:
    param:
      classname: DebugPDO
test:
  propel:
    param:
      classname: DebugPDO
all:
  propel:
    class: sfPropelDatabase
    param:
      classname: PropelPDO
      dsn: 'mysql:dbname=etapasvicom;host=mysql.etapasvi.com'
      username: saynt2day20
      password: 'Qq4mzp7Bfm'
      encoding: utf8
      persistent: true
      pooling: true
