mainSuccess:
  metas:
    title:        A message of peace, an appeal to the world

indexSuccess:
  metas:
    title:        News

showSuccess:
  metas:
    title:        News

feedSuccess:
  metas:
    title:        Feed

rssSuccess:
  has_layout:     off