mainSuccess:
  metas:
    title:        A message of peace to our world today

indexSuccess:
  metas:
    title:        News

showSuccess:
  metas:
    title:        News
    
teachingsSuccess:
  metas:
    title:        Teachings

feedSuccess:
  metas:
    title:        Feed

rssSuccess:
  has_layout:     off