# default values
all:
  site_name: SaveTapasviJungle.com
  protocol: http
  domain_name: www.savetapasvijungle.com
  
  domain_name_full: www.savetapasvijungle.com
  domain_name_mobile: www.savetapasvijungle.com
  
mobile:
  domain_name: www.savetapasvijungle.com
